namespace: stk
name: cloudformation
version: 1.0.1
readme: README.md
authors:
- John Woffindin <j.woffindin@gmail.com>
description: A collection of AWS CloudFormation modules using cfk-stk as a backend
license:
  - MIT
tags: [aws, cloudformation, stk]
repository: https://github.com/jwoffindin/stk.cloudformation
documentation: https://github.com/jwoffindin/stk.cloudformation
homepage: https://github.com/jwoffindin/stk.cloudformation
